# The logging configuration file for global adapter
######### root Level ########
logfile = "logs/adapter.log"
logLevel = "INFO"

[rotation]
MaxSize = 10    #meabytes
MaxBackups = 3
MaxAge =  2   #days
Compress = true

######### package Level ############
# LogLevels = "DEBG", "FATL", "ERRO", "WARN", "INFO", "PANC"

[[pkg]]
name = "github.com/wso2-enterprise/choreo-connect-global-adapter/internal/server"
logLevel = "INFO"
